version: '3.8'

services:
  app_1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_1
    volumes:
      - ./:/var/www
    networks:
      - traefik
  nginx1:
    image: nginx:alpine
    container_name: nginx1
    volumes:
      - ./:/var/www
      - ./docker/nginx/default1.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app_1
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app1.rule=Host(`app1.localhost`)"
      - "traefik.http.routers.app1.entrypoints=web"
      - "traefik.http.services.app1.loadbalancer.server.port=80"

  db:
    image: mysql:8.0
    container_name: clevory_db
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: secret
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - traefik
volumes:
  db_data:

networks:
  traefik:
    external: true
