version: '3.8'

services:
  app_1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_1
    volumes:
      - ./:/var/www
    networks:
      - internal

  nginx1:
    image: nginx:alpine
    container_name: nginx1
    volumes:
      - ./:/var/www
      - ./docker/nginx/default1.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app_1
    ports:
      - "80:80"  # Expose to host machine
    networks:
      - internal

  db:
    image: mysql:8.0
    container_name: clevory_db
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: secret
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - internal

volumes:
  db_data:

networks:
  internal:
    driver: bridge
